TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 3
  min_vel_x: 0.1
  max_vel_theta: 5
  min_vel_theta: -5
  min_in_place_vel_theta: 0.2
  escape_vel: -0.2
  holonomic_robot: true
  y_vels: [-2.5, -5, 5, 2.5]

  yaw_goal_tolerance: 6.28 #不在意角度误差，所以设为360°dwa
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  sim_time: 5.0
  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  control_frequency: 20