global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 1.0
   publish_frequency: 0.5
   static_map: false

   transform_tolerance: 0.5

   #plugins
   #costmap由很多图层组成master layer即最终决定global planner路径的图层（地图）
   #以下的plugins即要添加的图层

   plugins:
      - {name: static_layer,            type: "costmap_2d::StaticLayer"}
      - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
