TebLocalPlannerROS:
  odom_topic: "odom"
  map_frame: "map"


  # Robot
  acc_lim_x: 3.3
  acc_lim_theta: 1.5
  max_vel_x: 3
  max_vel_x_backwards: 2
  max_vel_theta: 1.2

  max_vel_y: 3
  acc_lim_y: 3.3


  footprint_model:
    type: "circular"
    radius: 0.21
    is_footprint_dynamic: false

  # GoalTolerance

  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.1
  free_goal_vel: true #Remove the goal velocity constraint such that the robot can arrive at the goal with maximum speed

  #Trajectory Configuration Parameters
  dt_ref: 0.3
  dt_hysteresis: 0.1
  min_samples: 3
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: -0.1
  max_global_plan_lookahead_dist: 3.0
  allow_init_with_backwards_motion: false #this is only recommended if the robot is equipped with rear sensors

  # Obstacles

  min_obstacle_dist: 0.4 #若规划碰到障碍提高该值
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.2
  inflation_dist: 0.6
  include_dynamic_obstacles: true

  #only if costmap_converter plugins are desired
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 3

  # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 0
  weight_acc_lim_y: 0
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1 # WE HAVE A HOLONOMIC ROBOT, JUST ADD A SMALL PENALTY
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1 # must be > 0
  weight_obstacle: 50
  weight_viapoint: 1
  weight_inflation: 0.1
  weight_adapt_factor: 2

  # Homotopy Class Planner

  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100
  selection_alternative_time_cost: false

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 1.0
  visualize_hc_graph: false
  viapoints_all_candidates: true
  switching_blocking_period: 0.0


